FROM nginx
COPY dist /usr/share/nginx/html
COPY ./default.conf.template /etc/nginx/templates/
LABEL org.opencontainers.image.source="https://github.com/gramps-project/gramps-web"
CMD ["nginx", "-g", "daemon off;"]
