blank_issues_enabled: false
contact_links:
  - name: Gramps Forum
    url: https://gramps.discourse.group/c/gramps-web/
    about: Please use the Gramps forum for general questions and support with deployment/setup issues.
