import translations from './lang/index.js'
/*
All strings that need to be translated
*/

export const additionalStrings = translations

export const grampsStrings = [
  '_Media Type:',
  '_Names',
  '_Save',
  'Abbreviation',
  'Abort changes?',
  'About',
  'Add an existing person as a child of the family',
  'Add an existing repository',
  'Add existing child to family',
  'Add',
  'Address Note',
  'Addresses',
  'Adopted',
  'Adult Christening',
  'After',
  'Age at death',
  'Age',
  'Agency',
  'Aide',
  'Album',
  'Also Known As',
  'Alternate Marriage',
  'and',
  'Annulment',
  'Archive',
  'Association Note',
  'Association',
  'Associations',
  'Attribute Note',
  'Attributes',
  'Audio',
  'Author',
  'Baptism',
  'Bar Mitzvah',
  'Bas Mitzvah',
  'Before',
  'Birth Date',
  'Birth Name',
  'Birth Place',
  'Birth',
  'Blessing',
  'Book',
  'Bookstore',
  'Borough',
  'Bride',
  'Building',
  'Burial',
  'Calculated',
  'Call name',
  'Call Number',
  'Cancel',
  'Card',
  'Caste',
  'Cause Of Death',
  'Cause',
  'Celebrant',
  'Cemetery',
  'Census',
  'Child Reference Note',
  'Children',
  'Christening',
  'Church',
  'Citation',
  'Citations',
  'City',
  'Civil Union',
  'Clear',
  'Clergy',
  'Collection',
  'Complete',
  'Con_fidence',
  'Confidence:',
  'Confidence',
  'Confirmation',
  'Country',
  'County',
  'Cremation',
  'Custom',
  'Dashboard',
  'Database overview',
  'Date',
  'Death Date',
  'Death Place',
  'Death',
  'Degree',
  'Department',
  'Description',
  'Details',
  'District',
  'Divorce Filing',
  'Divorce',
  'done',
  'Download',
  'E-mail',
  'Edit Citation',
  'Edit Event',
  'Edit Family',
  'Edit Media Object',
  'Edit Note',
  'Edit Person',
  'Edit Place',
  'Edit Repository',
  'Edit Source',
  'Education',
  'Elected',
  'Electronic',
  'Emigration',
  'Enclosed By',
  'Encloses',
  'Engagement',
  'Error',
  'Estimated',
  'Event Note',
  'Event Reference Note',
  'Event Type',
  'Event',
  'Events',
  'Families',
  'Family Note',
  'Family Tree',
  'Family',
  'Farm',
  'Father Age',
  'Father',
  'Female',
  'Feudal',
  'Fiche',
  'File',
  'Film',
  'First Communion',
  'Foster',
  'FTP',
  'Full Name',
  'Gallery',
  'Gender',
  'General',
  'Given name',
  'Given',
  'Graduation',
  'Gramps ID',
  'Groom',
  'Hamlet',
  'High',
  'Home Page',
  'Html code',
  'Identification Number',
  'Immigration',
  'in',
  'Informant',
  'Inherited',
  'Language',
  'Last changed',
  'Latitude',
  'LDS Note',
  'Library',
  'Link',
  'Loading items...',
  'Locality',
  'Location',
  'Longitude',
  'Low',
  'Magazine',
  'Male',
  'Manuscript',
  'Map',
  'Marriage Banns',
  'Marriage Contract',
  'Marriage Date',
  'Marriage License',
  'Marriage Settlement',
  'Marriage',
  'Married Name',
  'Married',
  'Matrilineal',
  'Matronymic',
  'Max Ancestor Generations',
  'Max descendant Generations',
  'Media Note',
  'Media Object',
  'Media Objects',
  'Media Reference Note',
  'Media',
  'Medical Information',
  'Military Service',
  'Mother Age',
  'Mother',
  'Municipality',
  'Name Note',
  'Name',
  'National Origin',
  'Naturalization',
  'Neighborhood',
  'New Citation',
  'New Event',
  'New Family',
  'New Media',
  'New Note',
  'New Person',
  'New Place',
  'New Repository',
  'New Source',
  'New Tag',
  'Newspaper',
  'Next',
  'Nick name',
  'Nickname',
  'No items',
  'No Home Person set.',
  'Nobility Title',
  'None',
  'Normal',
  'Not found',
  'Not Related',
  'Note',
  'Notes',
  'Number of Children',
  'Number of citations',
  'Number of events',
  'Number of families',
  'Number of generations:',
  'Number of individuals',
  'Number of Marriages',
  'Number of media',
  'Number of notes',
  'Number of people',
  'Number of places',
  'Number of repositories',
  'Number of sources',
  'Number of tags',
  'Number',
  'Occupation',
  'Ordination',
  'Page',
  'Parents',
  'Parish',
  'Participants',
  'Partner',
  'Password:',
  'Path',
  'Patrilineal',
  'Patronymic',
  'People',
  'Person Note',
  'Person',
  'Photo',
  'Place Note',
  'Place',
  'Places',
  'Prefix',
  'Previous',
  'Primary',
  'Private',
  'Probate',
  'Property',
  'Province',
  'Pseudonym',
  'Publication info',
  'Quality',
  'Range',
  'References',
  'Refresh',
  'Region',
  'Regular',
  'Relationship to _Father:',
  'Relationship to _Mother:',
  'Relationship to home person',
  'Relationship type:',
  'Relationships',
  'Religion',
  'Report',
  'Repositories',
  'Repository Note',
  'Repository Reference Note',
  'Repository',
  'Research',
  'Reset',
  'Residence',
  'Retirement',
  'Role',
  'Safe',
  'Second date',
  'Select a file',
  'Select a person as the father',
  'Select a person as the mother',
  'Select an existing media object',
  'Select an existing note',
  'Select an existing place',
  'Select an existing source',
  'Select...',
  'Select',
  'Selected',
  'self',
  'Set _Home Person',
  'Share an existing event',
  'Show Details',
  'Siblings',
  'Social Security Number',
  'Source Note',
  'Source Reference Note',
  'Source text',
  'Source: Author',
  'Source: Title',
  'Source',
  'Sources',
  'Span',
  'Sponsored',
  'Spouses',
  'State',
  'Statistics',
  'Stepchild',
  'Street',
  'Suffix',
  'Surname',
  'Surnames',
  'Tag',
  'Tags',
  'Taken',
  'Text',
  'This field is mandatory',
  'Time',
  'Timeline',
  'Title',
  'To Do',
  'Tombstone',
  'Town',
  'Transcript',
  'Type',
  'Unknown ',
  'Unknown',
  'Unmarried',
  'Use Compression',
  'Username: ',
  'Value',
  'Very High',
  'Very Low',
  'Video',
  'Village',
  'Web Home',
  'Web Search',
  'Web site',
  'Wife',
  'Will',
  'Witness',
  'Zoom'
]
