/**
 * Tests for gcalendar.js — all reference values generated by Gramps core
 * (gramps/gen/lib/gcalendar.py) running Python 3.
 *
 * Run with: npx vitest run gcalendar.test.js
 */

import {describe, expect, it} from 'vitest'
import {
  frenchSdn,
  frenchYmd,
  gregorianSdn,
  gregorianYmd,
  islamicSdn,
  islamicYmd,
  julianSdn,
  julianYmd,
  swedishSdn,
  swedishYmd,
  dateToSdn,
  CALENDARS,
} from '../../src/gcalendar.js'

// ── Gregorian ─────────────────────────────────────────────────────────────────

describe('gregorianSdn', () => {
  it.each([
    [2000, 6, 15, 2451711],
    [1970, 1, 1, 2440588],
    [1066, 10, 14, 2110695],
    [100, 3, 1, 1757644],
    [50, 6, 15, 1739488], // JS Date.UTC bug zone — correct value is NOT 2433448
    [1, 1, 1, 1721426],
    [-1, 1, 1, 1721060], // 2 BC
    [2024, 2, 29, 2460370], // leap day
  ])('gregorianSdn(%i, %i, %i) === %i', (y, m, d, expected) => {
    expect(gregorianSdn(y, m, d)).toBe(expected)
  })
})

describe('gregorianYmd', () => {
  it.each([
    [2451711, [2000, 6, 15]],
    [2440588, [1970, 1, 1]],
    [2110695, [1066, 10, 14]],
    [1757644, [100, 3, 1]],
    [1739488, [50, 6, 15]],
    [1721426, [1, 1, 1]],
    [1721060, [-1, 1, 1]],
    [2460370, [2024, 2, 29]],
  ])('gregorianYmd(%i) === %j', (sdn, expected) => {
    expect(gregorianYmd(sdn)).toEqual(expected)
  })
})

describe('gregorian round-trip', () => {
  it.each([
    [2000, 6, 15],
    [1066, 10, 14],
    [1, 1, 1],
    [-1, 1, 1],
    [50, 6, 15],
  ])('round-trips (%i, %i, %i)', (y, m, d) => {
    expect(gregorianYmd(gregorianSdn(y, m, d))).toEqual([y, m, d])
  })
})

// ── Julian ────────────────────────────────────────────────────────────────────

describe('julianSdn', () => {
  it.each([
    [2000, 6, 15, 2451724],
    [1066, 10, 14, 2110701],
    [1, 1, 1, 1721424],
    [-1, 1, 1, 1721058],
    [100, 3, 1, 1757643],
  ])('julianSdn(%i, %i, %i) === %i', (y, m, d, expected) => {
    expect(julianSdn(y, m, d)).toBe(expected)
  })
})

describe('julianYmd', () => {
  it.each([
    [2451724, [2000, 6, 15]],
    [2110701, [1066, 10, 14]],
    [1721424, [1, 1, 1]],
    [1721058, [-1, 1, 1]],
    [1757643, [100, 3, 1]],
  ])('julianYmd(%i) === %j', (sdn, expected) => {
    expect(julianYmd(sdn)).toEqual(expected)
  })
})

describe('julian round-trip', () => {
  it.each([
    [2000, 6, 15],
    [1066, 10, 14],
    [1, 1, 1],
    [-1, 1, 1],
  ])('round-trips (%i, %i, %i)', (y, m, d) => {
    expect(julianYmd(julianSdn(y, m, d))).toEqual([y, m, d])
  })
})

describe('julian vs gregorian divergence', () => {
  it('Julian 2000-06-15 is 13 SDN days ahead of Gregorian 2000-06-15', () => {
    expect(julianSdn(2000, 6, 15) - gregorianSdn(2000, 6, 15)).toBe(13)
  })
  it('Julian and Gregorian differ by 1 day at 100 AD', () => {
    expect(julianSdn(100, 3, 1)).toBe(1757643)
    expect(gregorianSdn(100, 3, 1)).toBe(1757644)
  })
})

// ── French Republican ─────────────────────────────────────────────────────────

describe('frenchSdn', () => {
  it.each([
    [1, 1, 1, 2375840],
    [3, 5, 10, 2376699],
    [8, 1, 14, 2378410],
  ])('frenchSdn(%i, %i, %i) === %i', (y, m, d, expected) => {
    expect(frenchSdn(y, m, d)).toBe(expected)
  })
})

describe('frenchYmd', () => {
  it.each([
    [2375840, [1, 1, 1]],
    [2376699, [3, 5, 10]],
    [2378410, [8, 1, 14]],
  ])('frenchYmd(%i) === %j', (sdn, expected) => {
    expect(frenchYmd(sdn)).toEqual(expected)
  })
})

describe('french round-trip', () => {
  it.each([
    [1, 1, 1],
    [3, 5, 10],
    [8, 1, 14],
  ])('round-trips (%i, %i, %i)', (y, m, d) => {
    expect(frenchYmd(frenchSdn(y, m, d))).toEqual([y, m, d])
  })
})

// ── Islamic ───────────────────────────────────────────────────────────────────

describe('islamicSdn', () => {
  it.each([
    [1, 1, 1, 1948440],
    [1445, 9, 15, 2460395],
    [1400, 1, 1, 2444199],
  ])('islamicSdn(%i, %i, %i) === %i', (y, m, d, expected) => {
    expect(islamicSdn(y, m, d)).toBe(expected)
  })
})

describe('islamicYmd', () => {
  it.each([
    [1948440, [1, 1, 1]],
    [2460395, [1445, 9, 15]],
    [2444199, [1400, 1, 1]],
  ])('islamicYmd(%i) === %j', (sdn, expected) => {
    expect(islamicYmd(sdn)).toEqual(expected)
  })
})

describe('islamic round-trip', () => {
  it.each([
    [1, 1, 1],
    [1445, 9, 15],
    [1400, 1, 1],
  ])('round-trips (%i, %i, %i)', (y, m, d) => {
    expect(islamicYmd(islamicSdn(y, m, d))).toEqual([y, m, d])
  })
})

// ── Swedish ───────────────────────────────────────────────────────────────────

describe('swedishSdn', () => {
  it.each([
    [1700, 3, 1, 2342042], // first day of Swedish calendar (Julian - 1)
    [1700, 3, 2, 2342043],
    [1712, 2, 28, 2346423],
    [1753, 3, 1, 2361390], // switch to Gregorian
    [2000, 1, 1, 2451545], // modern date: Gregorian
    [1699, 12, 31, 2341982], // before Swedish calendar: pure Julian
  ])('swedishSdn(%i, %i, %i) === %i', (y, m, d, expected) => {
    expect(swedishSdn(y, m, d)).toBe(expected)
  })
})

describe('swedishYmd', () => {
  it.each([
    [2342042, [1700, 3, 1]],
    [2342043, [1700, 3, 2]],
    [2346423, [1712, 2, 28]],
    [2346425, [1712, 2, 30]], // unique Swedish leap day (Feb 30!)
    [2361390, [1753, 3, 1]],
    [2451545, [2000, 1, 1]],
    [2341982, [1699, 12, 31]],
  ])('swedishYmd(%i) === %j', (sdn, expected) => {
    expect(swedishYmd(sdn)).toEqual(expected)
  })
})

// ── dateToSdn (unified entry point) ──────────────────────────────────────────

describe('dateToSdn', () => {
  it('returns 0 for all-zero date', () => {
    expect(dateToSdn(CALENDARS.GREGORIAN, 0, 0, 0)).toBe(0)
  })
  it('zero-adjusts missing day to 1', () => {
    expect(dateToSdn(CALENDARS.GREGORIAN, 2000, 6, 0)).toBe(
      gregorianSdn(2000, 6, 1)
    )
  })
  it('zero-adjusts missing month and day to 1', () => {
    expect(dateToSdn(CALENDARS.GREGORIAN, 2000, 0, 0)).toBe(
      gregorianSdn(2000, 1, 1)
    )
  })
  it('dispatches to julian', () => {
    expect(dateToSdn(CALENDARS.JULIAN, 2000, 6, 15)).toBe(2451724)
  })
  it('dispatches to french', () => {
    expect(dateToSdn(CALENDARS.FRENCH, 1, 1, 1)).toBe(2375840)
  })
  it('dispatches to islamic', () => {
    expect(dateToSdn(CALENDARS.ISLAMIC, 1, 1, 1)).toBe(1948440)
  })
  it('dispatches to swedish', () => {
    expect(dateToSdn(CALENDARS.SWEDISH, 2000, 1, 1)).toBe(2451545)
  })
  it('throws for unimplemented calendar (Hebrew=2)', () => {
    expect(() => dateToSdn(CALENDARS.HEBREW, 5784, 1, 1)).toThrow()
  })
})
