name: Build Docker release images

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set release version
        if: github.event_name == 'release'
        run: |
          TAG=${{ github.event.release.tag_name }}
          VERSION=${TAG#v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: tag and push release image
        if: github.event_name == 'release'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/gramps-project/grampsweb:${{ env.VERSION }},ghcr.io/gramps-project/grampsweb:latest
      - name: Clean up dangling images
        run: docker image prune -f -a
      - name: tag and push release nginx image
        if: github.event_name == 'release'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.nginx
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/gramps-project/grampsjs:${{ env.VERSION }},ghcr.io/gramps-project/grampsjs:latest
