name: Unit test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install
        run: npm ci
      - name: ESLint
        run: npm run lint:eslint
      - name: Prettier
        run: npm run lint:prettier
      - name: Build
        run: npm run build
      - name: Type check
        run: npm run typecheck
      - name: Unit tests
        run: npm test
