import { html } from 'lit';
import '../src/components/GrampsjsPlace.js';

export default {
  title: 'grampsjs-place',
};

const strings = {'Enclosed by': 'Teil von', 'Associations': 'Verknüpfungen', 'and': 'und', 'Addresses': 'Adressen', 'Attributes': 'Attribute', 'Author': 'Autor', 'Birth Date': 'Geburtsdatum', 'Borough': 'Borough', 'Building': 'Gebäude', 'Children': 'Kinder', 'Citation': 'Fundstelle', 'Citations': 'Fundstellen', 'City': 'Stadt', 'Country': 'Land', 'County': 'Kreis', 'Custom': 'Selbst definiert', 'Dashboard': 'Gramplet Werkzeugbank', 'Database overview': 'Datenbankübersicht', 'Date': 'Datum', 'Death Date': 'Sterbedatum', 'Department': 'Amt', 'Description': 'Beschreibung', 'Details': 'Details', 'District': 'Bezirk', 'Event': 'Ereignis', 'Event Type': 'Ereignisart', 'Events': 'Ereignisse', 'Families': 'Familien', 'Family Tree': 'Stammbaum', 'Family': 'Familie', 'Farm': 'Hof', 'Father': 'Vater', 'Gallery': 'Galerie', 'Given name': 'Vorname', 'Gramps ID': 'Gramps-ID', 'Hamlet': 'Weiler', 'Home Page': 'Homepage', 'in': 'in', 'Locality': 'Lokalität', 'Map': 'Karte', 'Marriage Date': 'Hochzeitsdatum', 'Married': 'Verheiratet', 'Media': 'Medien', 'Mother': 'Mutter', 'Municipality': 'Gemeinde', 'Name': 'Name', 'Neighborhood': 'Viertel', 'Note': 'Notiz', 'Notes': 'Notizen', 'Number of events': 'Anzahl der Ereignisse', 'Number of families': 'Familienanzahl', 'Number of generations:': 'Anzahl der Generationen:', 'Number of individuals': 'Personenzahl', 'Number of places': 'Anzahl der Orte', 'Number': 'Standortnummer/Signatur', 'Parents': 'Eltern', 'Parish': 'Kirchengemeinde', 'People': 'Personen', 'Place': 'Ort', 'Places': 'Orte', 'Primary': 'Primär', 'Province': 'Provinz', 'Publication info': 'Veröffentlichungsinformation', 'References': 'Referenzen', 'Region': 'Region', 'Relationships': 'Beziehungen', 'Repositories': 'Aufbewahrungsorte', 'Repository': 'Aufbewahrungsort', 'Siblings': 'Geschwister', 'Source': 'Quelle', 'Sources': 'Quellen', 'Spouses': '(Ehe-)Partner', 'State': 'Bundesland', 'Street': 'Straße', 'Surname': 'Nachname', 'Town': 'Kleinstadt', 'Type': 'Art', 'Unknown': 'Unbekannt', 'Village': 'Dorf', 'Zoom': 'Zoom'}



const place = [{"alt_loc": [], "alt_names": [], "backlinks": {"event": ["a5af0ed2bd00d5536b8"]}, "change": 1234390424, "citation_list": [], "code": "", "extended": {"backlinks": {"event": [{"attribute_list": [], "change": 1284030613, "citation_list": [], "date": {"calendar": 0, "dateval": [18, 2, 1916, false], "format": null, "modifier": 0, "newyear": 0, "quality": 0, "sortval": 2420912, "text": "", "year": 1916}, "description": "Death of Quinn, Abram", "gramps_id": "E2483", "handle": "a5af0ed2bd00d5536b8", "media_list": [], "note_list": [], "place": "00BKQC7SA8C9NCGB0A", "private": false, "tag_list": [], "type": "Death"}]}, "citations": [], "media": [], "notes": [], "tags": []}, "gramps_id": "P0852", "handle": "00BKQC7SA8C9NCGB0A", "lat": "28.9005446", "long": "-81.2636738", "media_list": [], "name": {"date": {"calendar": 0, "dateval": [0, 0, 0, false], "format": null, "modifier": 0, "newyear": 0, "quality": 0, "sortval": 0, "text": "", "year": 0}, "lang": "", "value": "Deltona"}, "note_list": [], "place_type": "City", "placeref_list": [{"date": {"calendar": 0, "dateval": [0, 0, 0, false], "format": null, "modifier": 0, "newyear": 0, "quality": 0, "sortval": 0, "text": "", "year": 0}, "ref": "c96587264d513cb56c90efab74d"}], "private": false, "tag_list": [], "title": "Deltona, FL", "urls": []}];

export const App = () =>
  html`
    <grampsjs-place .data=${place[0]} .strings=${strings}></grampsjs-place>
  `;
