import { html } from 'lit';
import '../src/components/GrampsjsMediaObject.js';

export default {
  title: 'grampsjs-media-object',
};

const data = {
  attribute_list: [],
  backlinks: {
    person: ['GNUJQCL9MD64AM56OH', 'AWFKQCJELLUWDY2PD3'],
    place: ['YNUJQC8YM5EGRG868J'],
  },
  change: 1328027353,
  checksum: '352c7ae13b8b642471ecae6fa78ce206',
  citation_list: [],
  date: {
    calendar: 0,
    dateval: [0, 0, 1897, false],
    format: null,
    modifier: 0,
    newyear: 0,
    quality: 0,
    sortval: 2413926,
    text: '',
    year: 1897,
  },
  desc: '1897_expeditionsmannschaft_rio_a',
  extended: {
    backlinks: {
      person: [
        {
          address_list: [
            {
              citation_list: ['c140d5aa362797c32d4'],
              city: 'Washington DC',
              country: 'USA',
              county: '',
              date: {
                calendar: 0,
                dateval: [2, 1, 2000, false],
                format: null,
                modifier: 0,
                newyear: 0,
                quality: 0,
                sortval: 2451546,
                text: '',
                year: 2000,
              },
              locality: '',
              note_list: [],
              phone: '',
              postal: '',
              private: false,
              state: 'District of Columbia',
              street: '1600 Pennsylvania Ave.',
            },
          ],
          alternate_names: [
            {
              call: '',
              citation_list: ['c140d25ef1c0e90ee81'],
              date: {
                calendar: 0,
                dateval: [0, 0, 0, false],
                format: null,
                modifier: 0,
                newyear: 0,
                quality: 0,
                sortval: 0,
                text: '',
                year: 0,
              },
              display_as: 0,
              famnick: '',
              first_name: 'Louis',
              group_as: '',
              nick: '',
              note_list: ['ac380498bac48eedee8'],
              private: false,
              sort_as: 0,
              suffix: '',
              surname_list: [
                {
                  connector: '',
                  origintype: '',
                  prefix: '',
                  primary: true,
                  surname: 'Garner',
                },
              ],
              title: '',
              type: 'Also Known As',
            },
            {
              call: '',
              citation_list: [],
              date: {
                calendar: 0,
                dateval: [0, 0, 0, false],
                format: null,
                modifier: 0,
                newyear: 0,
                quality: 0,
                sortval: 0,
                text: '',
                year: 0,
              },
              display_as: 0,
              famnick: '',
              first_name: 'Louie',
              group_as: '',
              nick: '',
              note_list: [],
              private: false,
              sort_as: 0,
              suffix: '',
              surname_list: [
                {
                  connector: '',
                  origintype: '',
                  prefix: '',
                  primary: true,
                  surname: 'Garner',
                },
              ],
              title: '',
              type: 'Other Name',
            },
          ],
          attribute_list: [
            {
              citation_list: [],
              note_list: [],
              private: false,
              type: 'Nickname',
              value: 'Big Louie',
            },
            {
              citation_list: ['c140d5e5dbf300411bf'],
              note_list: [],
              private: true,
              type: 'Social Security Number',
              value: '123-456-7890',
            },
            {
              citation_list: [],
              note_list: [],
              private: false,
              type: 'Description',
              value: '10 fingers, 10 toes.',
            },
          ],
          birth_ref_index: 0,
          change: 1431174904,
          citation_list: [
            'c140d25efc045ab2ea5',
            'c140d25efe703834da4',
            'c140d53ab8b377b4174',
          ],
          death_ref_index: 1,
          event_ref_list: [
            {
              attribute_list: [
                {
                  citation_list: ['c140d7c7bdc1fedb030'],
                  note_list: [],
                  private: false,
                  type: 'Father Age',
                  value: '28',
                },
              ],
              note_list: [],
              private: false,
              ref: 'a5af0ecb107303354a0',
              role: 'Primary',
            },
            {
              attribute_list: [],
              note_list: [],
              private: false,
              ref: 'a5af0ecb11f5ac3110e',
              role: 'Primary',
            },
            {
              attribute_list: [],
              note_list: [],
              private: false,
              ref: 'a5af0ecb12e29af8a5d',
              role: 'Primary',
            },
          ],
          family_list: ['9OUJQCBOHW9UEK9CNV'],
          gender: 1,
          gramps_id: 'I0044',
          handle: 'GNUJQCL9MD64AM56OH',
          lds_ord_list: [
            {
              citation_list: ['c140d73a2ca52f37800'],
              date: {
                calendar: 0,
                dateval: [0, 0, 1875, false],
                format: null,
                modifier: 0,
                newyear: 0,
                quality: 0,
                sortval: 2405890,
                text: '',
                year: 1875,
              },
              famc: '8OUJQCUVZ0XML7BQLF',
              note_list: [],
              place: 'WTAKQCGG8L8LYZCSBB',
              private: false,
              status: 13,
              temple: 'ADELA',
              type: 2,
            },
          ],
          media_list: [
            {
              attribute_list: [
                {
                  citation_list: ['c140d70b6ab7515c3f2'],
                  note_list: [],
                  private: false,
                  type: 'Age',
                  value: '50',
                },
              ],
              citation_list: ['c140d6cb9fe7fc1d3cc'],
              note_list: [],
              private: false,
              rect: [],
              ref: 'B1AUFQV7H8R9NR4SZM',
            },
            {
              attribute_list: [],
              citation_list: [],
              note_list: [],
              private: false,
              rect: [51, 19, 59, 33],
              ref: '238CGQ939HG18SS5MG',
            },
          ],
          note_list: [
            'ac380498c020c7bcdc7',
            'b39ff01f75c1f76859a',
            'b39ff11d8912173cded',
            'c140d4c29520c92055c',
          ],
          parent_family_list: ['8OUJQCUVZ0XML7BQLF'],
          person_ref_list: [
            {
              citation_list: ['c140d694e647717b683'],
              note_list: [],
              private: false,
              ref: 'VJFKQCFO7WESWPNKHE',
              rel: 'Godfather',
            },
          ],
          primary_name: {
            call: 'Anderson',
            citation_list: ['c140d56d19a1ced4c7a'],
            date: {
              calendar: 0,
              dateval: [1, 4, 1875, false],
              format: null,
              modifier: 0,
              newyear: 0,
              quality: 0,
              sortval: 2405980,
              text: '',
              year: 1875,
            },
            display_as: 0,
            famnick: 'Beauregard',
            first_name: 'Lewis Anderson',
            group_as: '',
            nick: 'Big Louie',
            note_list: [],
            private: false,
            sort_as: 0,
            suffix: 'Sr',
            surname_list: [
              {
                connector: '',
                origintype: 'Taken',
                prefix: '',
                primary: true,
                surname: 'Garner',
              },
              {
                connector: '',
                origintype: 'Inherited',
                prefix: 'von',
                primary: false,
                surname: 'Zieliński',
              },
            ],
            title: 'Dr.',
            type: 'Birth Name',
          },
          private: false,
          tag_list: ['bb80c2b235b0a1b3f49'],
          urls: [
            {
              desc: '',
              path: 'http://www.gramps-project.org/',
              private: false,
              type: 'Web Home',
            },
          ],
        },
        {
          address_list: [],
          alternate_names: [],
          attribute_list: [],
          birth_ref_index: 0,
          change: 1431174900,
          citation_list: ['c140d256751453509c7'],
          death_ref_index: 2,
          event_ref_list: [
            {
              attribute_list: [],
              note_list: [],
              private: false,
              ref: 'a5af0eb81f41c2992d2',
              role: 'Primary',
            },
            {
              attribute_list: [],
              note_list: [],
              private: false,
              ref: 'a5af0ed60de7a612b9e',
              role: 'Witness',
            },
            {
              attribute_list: [],
              note_list: [],
              private: false,
              ref: 'a5af0eb820536582433',
              role: 'Primary',
            },
            {
              attribute_list: [],
              note_list: [],
              private: false,
              ref: 'a5af0eb821402335276',
              role: 'Primary',
            },
          ],
          family_list: ['3XFKQCE7QUDJ99AVNV'],
          gender: 1,
          gramps_id: 'I1123',
          handle: 'AWFKQCJELLUWDY2PD3',
          lds_ord_list: [],
          media_list: [
            {
              attribute_list: [],
              citation_list: [],
              note_list: [],
              private: false,
              rect: [15, 27, 25, 43],
              ref: '238CGQ939HG18SS5MG',
            },
          ],
          note_list: [],
          parent_family_list: ['8OUJQCUVZ0XML7BQLF'],
          person_ref_list: [],
          primary_name: {
            call: '',
            citation_list: [],
            date: {
              calendar: 0,
              dateval: [0, 0, 0, false],
              format: null,
              modifier: 0,
              newyear: 0,
              quality: 0,
              sortval: 0,
              text: '',
              year: 0,
            },
            display_as: 0,
            famnick: '',
            first_name: 'Robert F.',
            group_as: '',
            nick: '',
            note_list: [],
            private: false,
            sort_as: 0,
            suffix: '',
            surname_list: [
              {
                connector: '',
                origintype: '',
                prefix: '',
                primary: true,
                surname: 'Garner',
              },
            ],
            title: '',
            type: 'Birth Name',
          },
          private: false,
          tag_list: [],
          urls: [],
        },
      ],
      place: [
        {
          alt_loc: [],
          alt_names: [],
          change: 1328027392,
          citation_list: ['c140df00ffa3ee017da'],
          code: '',
          gramps_id: 'P1678',
          handle: 'YNUJQC8YM5EGRG868J',
          lat: '42.5629668',
          long: '-114.4608711',
          media_list: [
            {
              attribute_list: [
                {
                  citation_list: ['c140dfa92f0109adfd4'],
                  note_list: [],
                  private: false,
                  type: 'Nickname',
                  value: 'Fred',
                },
              ],
              citation_list: ['c140df53c2710e5b0a9'],
              note_list: [],
              private: false,
              rect: [],
              ref: '238CGQ939HG18SS5MG',
            },
          ],
          name: {
            date: {
              calendar: 0,
              dateval: [0, 0, 0, false],
              format: null,
              modifier: 0,
              newyear: 0,
              quality: 0,
              sortval: 0,
              text: '',
              year: 0,
            },
            lang: '',
            value: 'Twin Falls',
          },
          note_list: [],
          place_type: 'City',
          placeref_list: [
            {
              date: {
                calendar: 0,
                dateval: [0, 0, 0, false],
                format: null,
                modifier: 0,
                newyear: 0,
                quality: 0,
                sortval: 0,
                text: '',
                year: 0,
              },
              ref: 'c965872719e5db6bfe5fc47b033',
            },
          ],
          private: false,
          tag_list: [],
          title: 'Twin Falls, ID',
          urls: [],
        },
      ],
    },
    citations: [],
    notes: [],
    tags: [
      {
        change: 1288512442,
        color: '#efb60c280c28',
        handle: 'bb80c2b235b0a1b3f49',
        name: 'ToDo',
        priority: 0,
      },
    ],
  },
  gramps_id: 'O0010',
  handle: '238CGQ939HG18SS5MG',
  mime: 'image/jpeg',
  note_list: [],
  path: '1897_expeditionsmannschaft_rio_a.jpg',
  private: false,
  tag_list: ['bb80c2b235b0a1b3f49'],
};

export const App = () =>
  html` <grampsjs-media-object .data="${data}"></grampsjs-media-object> `;
